version: '3'
services:
  web-client:
    image: rshokar/web-client:latest
    build:
      context: ./trucking-app-web
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  flask-api:
    image: rshokar/flask-api:latest
    build:
      context: ./trucking-app-flask
      dockerfile: Dockerfile
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    env_file:
      - ./trucking-app-flask/.env
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web-client
      - flask-api
