version: '3'
services:
  web-client:
    image: rshokar/web-client:latest
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://34.216.125.64
    env_file: ./trucking-app-web/.env
    ports:
      - "3000:80"

  flask-api:
    image: rshokar/flask-api:latest
    restart: unless-stopped
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    env_file:
      - ./trucking-app-flask/.env
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web-client
      - flask-api
