version: '3'
services:
  web-client:
    image: rshokar/web-client:latest
    build: ./trucking-app-web/.
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://34.216.125.64
    env_file: ./trucking-app-web/.env
    ports:
      - "3000:80"

  flask-api:
    image: rshokar/flask-api:latest
    build: ./trucking-app-flask/.
    restart: unless-stopped
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    env_file:
      - ./trucking-app-flask/.env
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - cert_data:/etc/letsencrypt
      - webroot:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-client
      - flask-api

  certbot:
    image: certbot/certbot
    volumes:
      - cert_data:/etc/letsencrypt
      - webroot:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

volumes:
  cert_data:
  webroot:
