version: '3'
services:
  web-client:
    image: rshokar/web-client:latest
    restart: unless-stopped
    ports:
      - "3000:80"

  flask-api:
    image: rshokar/flask-api:latest
    restart: unless-stopped
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      FLASK_DEBUG: ${FLASK_DEBUG}
      OPERATOR_AUTH_TOKEN_SECRET: ${OPERATOR_AUTH_TOKEN_SECRET}
      SEND_OPERATOR_RFO_TOKEN_SECRET: ${SEND_OPERATOR_RFO_TOKEN_SECRET}
      OPERATOR_ACCESS_TOKEN_SECRET: ${OPERATOR_ACCESS_TOKEN_SECRET}
      RESET_PASSWORD_SECRET: ${RESET_PASSWORD_SECRET}
      RESET_PASSWORD_SALT: ${RESET_PASSWORD_SALT}
      RESET_PASSWORD_CODE_EXPIRY: ${RESET_PASSWORD_CODE_EXPIRY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      SES_MAIL_SERVER: ${SES_MAIL_SERVER}
      SES_MAIL_PORT: ${SES_MAIL_PORT}
      SES_MAIL_USERNAME: ${SES_MAIL_USERNAME}
      SES_MAIL_PASSWORD: ${SES_MAIL_PASSWORD}
      MAX_CONTENT_SIZE: ${MAX_CONTENT_SIZE}
      AUTHORIZATION_HEADER: ${AUTHORIZATION_HEADER}
      WEB_URL: ${WEB_URL}
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web-client
      - flask-api
