from .dispatch_validation import dispatch_validation
from .operator_validation import operator_validation, operator_update
from .rfo_validation import rfo_validation, rfo_update
from .billing_ticket_validation import billing_ticket_validation, billing_ticket_upate
from .company_validations import company_validation, company_update
from .auth_validations import auth_validation, register_validation
from .customer_validations import customer_validation, customer_update
from .dispatch_validation import dispatch_validation, dispatch_update
